services: 
  frontendimg:  
    build:  /home/ec2-user/3-tier-architecture-using-DockerImages/Frontend/
    container_name: frontend
    ports: 
      - "80:80"
    depends_on: 
      - backendimg
    network_mode:
        bridge

  backendimg:
    build: /home/ec2-user/3-tier-architecture-using-DockerImages/Backend/
    container_name : backend
    ports: 
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - databaseimg
    network_mode:
        bridge

  databaseimg:
    build: /home/ec2-user/3-tier-architecture-using-DockerImages/Database/
    container_name: studentdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: student_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode:
        bridge